Leaveapp/urls.py
from django.urls import path
from .views import Dashboard,ProcurementApplicationCreate,ProcurementApplicationDetail,ProcurementApplicationUpdate,ProcurementApplicationDelete


app_name ='twx'

urlpatterns = [
#    path('', TemplateView.as_view(template_name='ahinventoryhome.html'),name='search'),
    path('',Dashboard.as_view(),name='home'),
    path('create', ProcurementApplicationCreate.as_view(),name='application-create'),
    path('app/<int:pk>', ProcurementApplicationDetail.as_view(), name='application-detail'),
    path('app/<int:pk>/', ProcurementApplicationUpdate.as_view(), name='application-update'),
    path('app/<int:pk>/delete/', ProcurementApplicationDelete.as_view(), name='application-delete'),
    ]

TWX/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('twx/',include('Leaveapp.urls',namespace='twx')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Leaveapp/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.contrib.auth.models import AbstractUser
from river.models.fields.state import StateField
from djmoney.models.fields import MoneyField
from django_fsm import transition, FSMIntegerField
from crum import get_current_user
from django.utils import timezone
from enum import Enum
import datetime
#from audit_log.models import AuthStampedModel
# Create your models here.
class OrgUnit(MPTTModel):
    TYPES = (
        ('Corp', 'Corporation'),
        ('Dir', 'Directorate'),
        ('Div', 'Division'),
        ('Dept', 'Department'),
        ('Unit', 'Unit'),
    )
    entity_name = models.CharField(max_length=50,blank=False,unique=True)
    entity_type = models.CharField(max_length=50,choices=TYPES)
#    entity_head = models.ForeignKey(Employee,related_name='entity_head',on_delete=models.CASCADE,null=False,blank=False)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    def __str__(self):
        return self.entity_name


class Employee(AbstractUser):
    ROLES = (
        ('Presdir', 'President Director'),
        ('Director', 'Director'),
        ('Division Head', 'Division Head'),
        ('Department Head', 'Department Head'),
        ('Unit Head', 'Unit Head'),
        ('Staff','Staff'),
    )
    username = models.CharField(max_length=200,blank=False,unique=True)
    email = models.EmailField(max_length=200,unique=False,blank=False)
    role = models.CharField(max_length=50,choices=ROLES,blank=False)
    is_admin = models.BooleanField(default=False)
    org_unit = models.ForeignKey(OrgUnit,on_delete=models.CASCADE,null=True,blank=False)
    def __str__(self):
        return self.username


class LeaveApplication(models.Model):
    LeaveDateStart = models.DateField()
    LeaveDateEnd = models.DateField()
#   state_field = StateField()
    
    class Meta:
        permissions = (("can_approve_level1","Can approve level 1"),
                       ("can_reject_level1","Can reject level 1(unit deparment level level)"),
                       ("can_approve_level2","Can approve level 2"),
                       ("can_reject_level2","Can reject level 2(division level)"),
                       ("can_approve_level3","Can approve level 3"),
                       ("can_reject_level3","Can reject level 3(directorat level)"),                       
                       )

class RevisionComment(models.Model):
    created_by       = models.ForeignKey(Employee,related_name='%(class)s_createdby',on_delete=models.CASCADE)
    modified_by      = models.ForeignKey(Employee,related_name='%(class)s_modifiedby',null=True,blank=True,on_delete=models.CASCADE)
    created_on       = models.DateTimeField(auto_now_add=True)
    modified_on      = models.DateTimeField(auto_now=True)
    related_application = models.ForeignKey('ProcurementApplication',related_name='%(class)s_application',on_delete=models.CASCADE)
    comment          = models.TextField()


class StateEnum(Enum):
    CANCELLED = 0
    CREATED = 1
    REJECTED = 2
    DIRS_APPROVED =3
    PD_APPROVED = 4
    
STATES = ('CANCELLED', 'CREATED', 'CHECKED','RETURNED', 'APPROVED', 'REJECTED')
STATES = list(zip(STATES, STATES))

class ProcurementApplication(models.Model):
    CANCELLED = 0
    CREATED = 1
    REVISED = 2
    CHECKED = 3
    RETURNED = 4
    APPROVED = 5
    STATUS_CHOICES = (
        (CANCELLED, 'cancelled'),
        (CREATED, 'created'),
        (REVISED,'revised'),
        (CHECKED, 'checked'),
        (RETURNED, 'returned'),
        (APPROVED, 'approved'),
    )
    created_by       = models.ForeignKey(Employee,related_name='%(class)s_createdby',on_delete=models.CASCADE)
    modified_by      = models.ForeignKey(Employee,related_name='%(class)s_modifiedby',null=True,blank=True,on_delete=models.CASCADE)
    created_on       = models.DateTimeField(auto_now_add=True)
    modified_on      = models.DateTimeField(auto_now=True)
    purpose          = models.CharField(max_length=200,blank=False,unique=False)
    amount           = MoneyField(max_digits=15,decimal_places=0,default_currency='IDR')
    document         = models.FileField(max_length=100,upload_to='documents')
    status = FSMIntegerField(choices=STATUS_CHOICES,default=CREATED,protected=True)
    #status = FSMIntegerField(default=StateEnum.CREATED,protected=True) 
    #status = FSMField(default=STATES[1], choices=STATES)
    
    def __str__(self):
        return self.purpose    
    

    class Meta:
        permissions = (("can_cancel","Can cancel"),
                       ("can_check","Can check and return"),
                       ("can_approve","can approve and reject"),                     
                       )
    
    def is_dir(self):
        current_user = get_current_user()
        return current_user.role=='Director'
    
    def is_presdir(self):
        current_user = get_current_user()
        return current_user.role=='Presdir'
        
    @transition(field=status,source=[CREATED,RETURNED],target=CANCELLED,permission='can_cancel')
    def do_cancel(self):
        pass
        
    @transition(field=status,source=RETURNED,target=REVISED,permission='can_cancel')
    def do_revise(self):
        self.modified_by=get_current_user()
        self.modified_on=datetime.datetime.now()
        pass
        
    @transition(field=status,source=[CREATED,REVISED],target=CHECKED,permission='can_check')
    def do_check(self):
        self.modified_by=get_current_user()
        self.modified_on=datetime.datetime.now()
        pass
        
    
    @transition(field=status,source=[CREATED,REVISED],target=RETURNED,permission='can_check')
    def do_return(self):
        self.modified_by=get_current_user()
        self.modified_on=datetime.datetime.now()
        pass
    
    @transition(field=status,source=CHECKED,target=APPROVED,permission='can_approve')
    def do_approve(self):
        self.modified_by=get_current_user()
        self.modified_on=datetime.datetime.now()
        pass
        
    @transition(field=status,source=CHECKED,target=RETURNED,permission='can_approve')
    def do_reject(self):
        self.modified_by=get_current_user()
        self.modified_on=datetime.datetime.now()
        pass
        

        

Leaveapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Employee

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = Employee
        fields = ('username', 'email','role','org_unit')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = Employee
        fields = ('username', 'email','role','org_unit')

Leaveapp/views.py
from django.shortcuts import render,redirect
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic.detail import DetailView
from .models import ProcurementApplication,Employee,RevisionComment
from django.contrib.auth.models import User,Permission
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from crum import get_current_user
from django.db.models import Q
from guardian.shortcuts import assign_perm,get_objects_for_user,get_user_perms,get_perms_for_model
from django.http import HttpResponseRedirect
import datetime
# Create your views here.
class Dashboard(TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, *args, **kwargs):
        context = super(Dashboard, self).get_context_data(*args, **kwargs)
        

        context['application']=ProcurementApplication.objects.all()
        return context
        
class ProcurementApplicationUpdate(UpdateView):
    model = ProcurementApplication
    fields = ['purpose','amount','document']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('twx:home')
    
    #def post(self,request,*args,**kwargs):
        #pk = self.kwargs.get('pk')
        #related_object = ProcurementApplication.objects.get(pk=pk)
        
    #    related_object.do_revise()
    #    related_object.save()
    #    return redirect(reverse_lazy('twx:home'))
        
    def form_valid(self, form):
        self.object = form.save()
        self.object.modified_on = datetime.datetime.now()
        self.object.modified_by = Employee.objects.get(username=self.request.user)
        self.object.do_revise()
        self.object.save()
        return redirect(reverse_lazy('twx:home'))
        
        
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        related_object = ProcurementApplication.objects.get(pk=pk)
        try:
            comment = RevisionComment.objects.filter(related_application=related_object)
        except RevisionComment.DoesNotExist:
            comment = None
        context['comment'] = comment
        return context
    
    
    
class ProcurementApplicationDelete(DeleteView):
    model = ProcurementApplication
    success_url = reverse_lazy('twx:home')
    
        
        
class ProcurementApplicationDetail(DetailView):
    model = ProcurementApplication
    
    def post(self, request, *args, **kwargs):
        revision_comment = request.POST.get('comment')
        checked = request.POST.get('check')
        returned = request.POST.get('return')
        approved = request.POST.get('approve')
        rejected = request.POST.get('reject')
        pk = self.kwargs.get('pk')

        related_object = ProcurementApplication.objects.get(pk=pk)
        #related_object.modified_by=get_current_user()
        #related_object.modified_on=datetime.datetime.now()
        app_revision = RevisionComment.objects.create(created_by=get_current_user(),related_application=related_object,comment=revision_comment)

        if checked:
            related_object.do_check()
            related_object.save()
        elif returned:
            related_object.do_return()
            related_object.save()
        elif approved:
            related_object.do_approve()
            related_object.save()
        elif rejected:
            related_object.do_reject()
            related_object.save()

        return redirect(reverse_lazy('twx:home'))
        
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        
        return context




class ProcurementApplicationCreate(LoginRequiredMixin,CreateView):
    login_url = 'login'
    model = ProcurementApplication
    fields = ['purpose','amount','document']
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('twx:home')
    

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        #return super().form_valid(form)
        self.object = form.save()
        #print("self.request ",get_current_user())
        
        ## Set 'can_cancel' permission to user who posted this application
        perm = Permission.objects.get(codename='can_cancel')
        current_user = Employee.objects.get(username=self.request.user)
        assign_perm(perm,current_user,self.object)
        #

        
        # Find out his superior whose designation is 'Director' then assign permission 'can_check' to him
        ancestor_dir = current_user.org_unit.get_ancestors(ascending=True).filter(entity_type='Dir')
        director = Employee.objects.filter(role='Director',org_unit__in=ancestor_dir)
        perm = Permission.objects.get(codename='can_check')
        assign_perm(perm,director,self.object)
        
        # Find out who the director of this company and assign permission 'can_approve' to him
        presdir = Employee.objects.filter(role='Presdir')
        perm = Permission.objects.get(codename='can_approve')
        assign_perm(perm,presdir,self.object)
        
         
        #print("permission ..=",assigned_to.has_perm('can_cancel',self.object))
        return HttpResponseRedirect(self.get_success_url())
        
    #def post(self,request):
    #    perm = Permission.objects.get(codename='can_cancel')
    #    assigned_to = Employee.objects.get(pk=self.request[id])
    #    assigned_object = ProcurementApplication.object.create(created_by= 
    #    assign_perm(perm,assigned_to,assigned

Leaveapp/templates/Leaveapp/dashboard.html
{% extends 'base.html' %}
{% block content %}
{% load guardian_tags %}
{% load custom_tags %}

<h2><center>TWX Dashboard</center></h2>
<div class="row">
  <div class="col-4">

	  <form action="{% url 'twx:application-create' %}">
         <button type="submit" class="btn btn-primary">New Application</button>
      </form> 
	  </div>
  <div class="col-4"></div>
  <div class="col-4">
	<div class="form-group" style="display: flex">      
		<label for="sel1">Search by:</label>
		  <select class="form-control" id="sel1" name="sellist1">
			<option>Date</option>
			<option>Applicant</option>
			<option>Purpose</option>
			<option>Amount</option>
			<option>Document</option>
		  </select>
	   <label for="comment">With keyword:</label>
		 <textarea class="form-control" rows="1" id="comment"></textarea>
	</div>
  </div>
</div>
<table class="table table-bordered table-sm">
  <thead class="thead-dark">
	  <tr>
		<th>Date</th>
		<th>Applicant</th>
		<th>Purpose</th>
		<th>Amount</th>
		<th>Document</th>
		<th>Approval Status</th>
		<th>Actions</th>
	  </tr>
  <thead>

	  


  {% for item in application %}
  	{% get_obj_perms request.user for item as "permission" %}
	  <tr>
		{% if "can_cancel" in permission %} 
		<td>{{item.created_on}}</td>
		<td>{{item.created_by}}</td>
		<td>{{item.purpose}}</td>
		<td>{{item.amount}}</td>
		<td><a href="some.pdf">quotation</a></td>
		<td>{% textify_status item.status %} by {{ item.modified_by }}</td>
		{% if item.status == 4 or item.status == 1 %}
			<td><a href="{% url 'twx:application-update' item.pk %}" class="btn btn-primary">Revise</a><a href="{% url 'twx:application-delete' item.pk %}" class="btn btn-primary">Cancel</a></td>
		{% endif %}
		{% elif "can_check" in permission %}
		 {% if item.status == 1 or item.status == 2 %}
			<td>{{item.created_on}}</td>
			<td>{{item.created_by}}</td>
			<td>{{item.purpose}}</td>
			<td>{{item.amount}}</td>
			<td><a href="some.pdf">quotation</a></td>
			<td>{% textify_status item.status %} by {{ item.modified_by }}</td>
			<td><form action="{% url 'twx:application-detail' item.pk %}"><button type="btn" class="btn btn-primary">Open to Check</button></form></td>
			{% endif %}
		{% elif "can_approve" in permission %} 
		  {% if item.status == 3 or item.status == 5 %}
			<td>{{item.created_on}}</td>
			<td>{{item.created_by}}</td>
			<td>{{item.purpose}}</td>
			<td>{{item.amount}}</td>
			<td><a href="some.pdf">quotation</a></td>
			<td>{% textify_status item.status %} by {{ item.modified_by }}</td>
			{%if item.status == 3 %}
			<td><form action="{% url 'twx:application-detail' item.pk %}"><button type="btn" class="btn btn-primary">Open to Check</button></form></td>
		    {% endif %}
		 {% endif %}
	{% endif %}
	  </tr>
  {% endfor %}

</table>

<div class="container">                
  <ul class="pagination justify-content-center">
    <li class="page-item"><a class="page-link" href="javascript:void(0);">Previous</a></li>
    <li class="page-item"><a class="page-link" href="javascript:void(0);">1</a></li>
    <li class="page-item"><a class="page-link" href="javascript:void(0);">2</a></li>
    <li class="page-item"><a class="page-link" href="javascript:void(0);">Next</a></li>
  </ul>
</div>

{% endblock %}

Leaveapp/templates/Leaveapp/procurementapplication_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

Leaveapp/templates/Leaveapp/procurementapplication_create_form.html
{% extends 'base.html' %}
{% block content %}
<div>
<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <button type="submit" name="save" value="save">Save</button>
    <button type="submit" name="another" value="another">Another</button>
</form>
</div> 
{% endblock %}

Leaveapp/templates/Leaveapp/procurementapplication_detail.html
{% extends 'base.html' %}
{% block content %}
{% load guardian_tags %}
<div>
{% get_obj_perms request.user for object as "permission" %}
    <table class="table table-bordered table-sm">
    <tr>
		<td>Created By</td>
		<td>{{ object.created_by }}</td>
    </tr>
    <tr>
		<td>Modified By</td>
		<td>{{ object.modified_by }}</td>
    </tr>
    <tr>
		<td>Created On</td>
		<td>{{ object.created_on }}</td>
    </tr>
    <tr>
		<td>Modified On</td>
		<td>{{ object.modified_on }}</td>
    </tr>
    <tr>
       <td>Purpose</td>
       <td>{{ object.purpose }}</td>
    </tr>
    <tr>
       <td>Amount</td>
       <td>{{ object.amount }}</td>
    </tr>
    </table>

	<form method="POST">
	{% csrf_token %}
	    <label for="fname">Comment:</label>
	    <textarea id="comment" rows="4" cols="50" name="comment"></textarea><br>
	   {% if 'can_check' in permission %}
		<button type="submit" name="check" value="ok">OK</button>
		<button type="submit" name="return" value="return">Return</button>
	   {% endif %}
	   {% if 'can_approve' in permission %}
		<button type="submit" name="approve" value="ok">approve</button>
		<button type="submit" name="reject" value="reject">Reject</button>
		{% endif %}
    </form>
</div> 
{% endblock %}

Leaveapp/templates/Leaveapp/procurementapplication_update_form.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="save" value="save">
    <div>
	<h1>Comments</h1>
	{% for item in comment %}
    <p>{{item.created_by}} - {{item.modified_on}}</p>
    <p>{{item.comment}}</p>
    {% endfor %}
    </div>
</form>
{% endblock %}